services:
  db:
    image: mongo:8.0
    restart: always
    command: ['mongod', '--bind_ip_all', '--replSet', 'rs0']
    ports: ['27017:27017']
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mongodb_data:
    driver: local

networks:
  user_app_network:
    name: user_app_network
